version: '3.8'

services:
  my_app:
    build:
      context: .
      dockerfile: stage1.Dockerfile

    expose:
      - '8080'
    deploy:
      replicas: 40
    restart: always
    environment:
      - PORT=8080
    networks:
      - front-network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on: 
      - my_app
    networks:
      - front-network

networks:
  front-network:
    driver: bridge